const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Dictionary,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Behaviors.destroy,
		C3.Plugins.Tilemap,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.HasChildren,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Browser: 0},
	{AJAX: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{Variables: 0},
	{suelo: 0},
	{Solid: 0},
	{pasto: 0},
	{health: 0},
	{xp: 0},
	{small: 0},
	{rock: 0},
	{name: 0},
	{damage: 0},
	{btnTool: 0},
	{bg_bar: 0},
	{Tween: 0},
	{bar_progress: 0},
	{tool_name: 0},
	{acid_rain: 0},
	{game_manager: 0},
	{bgUnlock: 0},
	{fade: 0},
	{btnEquip: 0},
	{unlock_picture: 0},
	{btnTool2: 0},
	{LevelTools: 0},
	{firerate: 0},
	{Timer: 0},
	{btnPower: 0},
	{power_name: 0},
	{bar_power_progress: 0},
	{bg_power_bar: 0},
	{Bullet: 0},
	{Fade: 0},
	{arrow_normal: 0},
	{Sine: 0},
	{ray: 0},
	{fireball: 0},
	{acid: 0},
	{delay: 0},
	{spikes: 0},
	{taladro: 0},
	{Platform: 0},
	{tnt: 0},
	{tnt_masc: 0},
	{DestroyOutsideLayout: 0},
	{laserball: 0},
	{laser_ray: 0},
	{XPLevels: 0},
	{Tilemap: 0},
	{background_: 0},
	{background_2: 0},
	{background_3: 0},
	{Equip_A_: 0},
	{rock_break: 0},
	{SpriteFont: 0},
	{background_4: 0},
	{Trees: 0},
	{Vegetation: 0},
	{laserball2: 0},
	{violet_fx: 0},
	{acid_explosion: 0},
	{title_unlock: 0},
	{txtFrase: 0},
	{hand: 0},
	{test: 0},
	{description: 0},
	{nindex: 0},
	{nindexunlock: 0},
	{price: 0},
	{btnUpdate: 0},
	{nIndex: 0},
	{line_update: 0},
	{coin: 0},
	{btnEquip2: 0},
	{bgPopUp: 0},
	{update_price: 0},
	{update_manager: 0},
	{btnUpdate2: 0},
	{txtPrice: 0},
	{txtBoss: 0},
	{boss_rock: 0},
	{txtXP: 0},
	{boss_incomeing: 0},
	{pasto2: 0},
	{Minerals: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newlayer: 0},
	{XP: 0},
	{TargetXP: 0},
	{Factor: 0},
	{Level: 0},
	{BossDestroyed: 0},
	{BOSSHEALTH: 0},
	{posX: 0},
	{posY: 0},
	{anim: 0},
	{cant_damage: 0},
	{mineral_id: 0},
	{xp_amount: 0},
	{power_up: 0},
	{cant: 0},
	{mineraID: 0},
	{arrow_angle: 0},
	{GAMENAME_SAVE: 0},
	{TOTLEVELS: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Variables: class extends self.IArrayInstance {},
	suelo: class extends self.ISpriteInstance {},
	pasto: class extends self.ISpriteInstance {},
	rock: class extends self.ISpriteInstance {},
	btnTool: class extends self.ISpriteInstance {},
	bg_bar: class extends self.ISpriteInstance {},
	bar_progress: class extends self.ITiledBackgroundInstance {},
	game_manager: class extends self.ISpriteInstance {},
	bgUnlock: class extends self.ISpriteInstance {},
	fade: class extends self.ISpriteInstance {},
	btnEquip: class extends self.ISpriteInstance {},
	unlock_picture: class extends self.ISpriteInstance {},
	btnTool2: class extends self.ISpriteInstance {},
	LevelTools: class extends self.IDictionaryInstance {},
	btnPower: class extends self.ISpriteInstance {},
	bar_power_progress: class extends self.ITiledBackgroundInstance {},
	bg_power_bar: class extends self.ISpriteInstance {},
	arrow_normal: class extends self.ISpriteInstance {},
	ray: class extends self.ISpriteInstance {},
	fireball: class extends self.ISpriteInstance {},
	acid: class extends self.ISpriteInstance {},
	spikes: class extends self.ISpriteInstance {},
	taladro: class extends self.ISpriteInstance {},
	tnt: class extends self.ISpriteInstance {},
	tnt_masc: class extends self.ISpriteInstance {},
	laserball: class extends self.ISpriteInstance {},
	laser_ray: class extends self.ISpriteInstance {},
	XPLevels: class extends self.IDictionaryInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	background_: class extends self.ISpriteInstance {},
	background_2: class extends self.ISpriteInstance {},
	background_3: class extends self.ISpriteInstance {},
	Equip_A_: class extends self.ISpriteInstance {},
	rock_break: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	background_4: class extends self.ISpriteInstance {},
	Trees: class extends self.ISpriteInstance {},
	Vegetation: class extends self.ISpriteInstance {},
	laserball2: class extends self.ISpriteInstance {},
	violet_fx: class extends self.ISpriteInstance {},
	acid_explosion: class extends self.ISpriteInstance {},
	title_unlock: class extends self.ISpriteInstance {},
	txtFrase: class extends self.ISpriteFontInstance {},
	hand: class extends self.ISpriteInstance {},
	test: class extends self.ISpriteInstance {},
	btnUpdate: class extends self.ISpriteInstance {},
	line_update: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	btnEquip2: class extends self.ISpriteInstance {},
	bgPopUp: class extends self.ISpriteInstance {},
	update_manager: class extends self.ISpriteInstance {},
	btnUpdate2: class extends self.ISpriteInstance {},
	txtPrice: class extends self.ISpriteFontInstance {},
	txtBoss: class extends self.ISpriteFontInstance {},
	boss_rock: class extends self.ISpriteInstance {},
	txtXP: class extends self.ISpriteFontInstance {},
	boss_incomeing: class extends self.ISpriteInstance {},
	pasto2: class extends self.ISpriteInstance {},
	Minerals: class extends self.ISpriteInstance {}
}